### ISSUE TITLE
Add Fixtures section

### ISSUE THREAD

**Issue by james-rae** [ramp4-pcar4/config-editor#1]
Need a way to define/edit fixture specific configuration.

- [x] Legend
- [x] Grid
- [x] Details
- [x] Basemap
- [x] Layer Reorder
- [x] Scrollguard
- [x] Settings
- [x] Geosearch
- [x] Export
- [x] Wizard
- [x] Areas of Interest
- [x] Appbar
- [x] Help
- [x] Hilight
- [x] Mapnav (I gotta plead ignorance on this one, maybe it should be higher)
- [x] Metadata
- [x] North Arrow
- [x] Overview Map

**Comment by mohsin-r** [comment]
- [ ] Areas of Interest
- [ ] Appbar
- [ ] Basemap
- [ ] Crosshairs
- [ ] Details
- [ ] Export
- [ ] Geosearch
- [ ] Grid
- [ ] Help
- [ ] Hilight
- [ ] Layer Reorder
- [ ] Legend
- [ ] Mapnav
- [ ] Metadata
- [ ] North Arrow
- [ ] Overview Map
- [ ] Panguard
- [ ] Scrollguard
- [ ] Settings
- [ ] Snowman
- [ ] Wizard

- [ ]

**Comment by mohsin-r** [comment]
The above task list has been added to track which fixture configs have completed implementation. If people feel that there are some high priority fixtures, feel free to comment below.

**Comment by dan-bowerman** [comment]
Rough re-order based on priority... as I see it from the previously constructed Storylines products:

- [ ] Legend
- [ ] Grid
- [ ] Details
- [ ] Basemap
- [ ] Layer Reorder
- [ ] Scrollguard
- [ ] Settings
- [ ] Geosearch
- [ ] Export
- [ ] Wizard
- [ ] Areas of Interest
- [ ] Appbar
- [ ] Help
- [ ] Crosshairs
- [ ] Hilight
- [ ] Mapnav (I gotta plead ignorance on this one, maybe it should be higher)
- [ ] Metadata
- [ ] North Arrow
- [ ] Overview Map
- [ ] Panguard
- [ ] Snowman
