### ISSUE TITLE
Investigate RAMP build behavior

### ISSUE THREAD

**Issue by james-rae** [ramp4-pcar4/config-editor#10]
From the update instructions:

> Go to the ramp.js file, and at the very end, add the line:
> `window.RAMP = RAMP;`

There were no reasons given for this other than "vite is disrespectful"

But it seems strange to me, since `ramp.js` should be adding a global `RAMP` var already.

Investigate 🕵️

**Comment by james-rae** [comment]
Even stranger, it appears this file isn't even being used (or I can't find where it is).
There is a script tag to it in the `index.html`, but the preview module (which is what spins up a RAMP on screen) is using `ramp.esm.js`. 
So it's like there is two builds of ramp in the repo. One being loaded on the demo page for _reasons_ and another being imported in typescript (so would get bundled when the config editor is built.

**Comment by mohsin-r** [comment]
Sorry I just saw this comment. The reason I also included the global `ramp.js` was mainly for testing and utility. It provides an easy way to access the `geo` module for default LODs and whatnot while initializing configs in the browser console. It probably is a good idea to clean up the whole 2 builds thing before release.

**Comment by mohsin-r** [comment]
This is no longer an issue since `RAMP.js` has been removed and is no longer needed.
