### ISSUE TITLE
Standalone HTML page for import/export of RAMP4 configs

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/config-editor#51]
This issue is to create an HTML landing page for accessing the config-editor and permitting an end-user to import, modify+preview, and export RAMP4 configurations. 

Ideally this page would be deployable anywhere, but @mohsin-r has mentioned he can include this in the existing [GitHub pages deployment](https://ramp4-pcar4.github.io/config-editor/).

**Comment by mohsin-r** [comment]
Completed in #52.
