### ISSUE TITLE
Demo / Sample Page

### ISSUE THREAD

**Issue by james-rae** [ramp4-pcar4/config-editor#9]
Would be nice to have a demo page. Just to look at.

Even fancier would have a file load / file save button. Then random lurkers can make all the configs they like via the UI.

**Comment by james-rae** [comment]
Basic demo was added. Leaving issue open since there is room to make it fancier.

https://ramp4-pcar4.github.io/config-editor/

**Comment by mohsin-r** [comment]
Fancier demo added in #52. Will leave this open as it would be better to incorporate GitHub Actions to make it work.

**Comment by mohsin-r** [comment]
Donethanks in #53 and #55.
